g=open(accountList, r)
pickle.load(adminUsers)
print("Welcome to AdminTools!")
print("Please enter your official AdminTools account credentials:")
print("NOTE: You may enter your PythonG Live account credentials if you have access.")
print("Please enter your admin username:")
adminu = input()
print("Please enter your admin password:")
adminp = input()
